FROM docker.openmodelica.org/build-deps:stretch.nightly.amd64

RUN true \
    && export DEBIAN_FRONTEND=noninteractive && apt-get update \
    && apt-get install -qyy git flex zip unzip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && rm -f control requirements.txt *.deb
