# FROM ubuntu:xenial
FROM openmodelica/openmodelica:v1.12.0
MAINTAINER Martin Sjölund <martin.sjolund@liu.se>

RUN apt-get update && apt-get upgrade -qy && apt-get dist-upgrade -qy\
    && apt-get install -qy gnupg wget ca-certificates apt-transport-https \
    && echo "deb https://build.openmodelica.org/omc/builds/linux/releases/1.12.0/ xenial release" > /etc/apt/sources.list.d/openmodelica.list \
    && wget https://build.openmodelica.org/apt/openmodelica.asc -O- | apt-key add - \
    && apt-get update && apt-get upgrade && apt-get dist-upgrade \
    && apt-get install -qy openmodelica omlib-modelica-3.2.1 omlib-modelica-3.2.2 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

WORKDIR /data
VOLUME ["/data"]
