ARG DISTRO=ubuntu:bionic
FROM ${DISTRO}
MAINTAINER Martin Sjölund <martin.sjolund@liu.se>
ENV DEBIAN_FRONTEND noninteractive

ADD https://svn.modelica.org/projects/Modelica/branches/tools/MoParser/Linux/moparser /usr/local/bin/moparser
RUN chmod +x /usr/local/bin/moparser \
    && apt-get update && apt-get install -qy libc6-i386 lib32stdc++6 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

WORKDIR /data
VOLUME ["/data"]
