FROM docker.openmodelica.org/build-deps:v1.16.4

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -qyy texlive-bibtex-extra \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
