FROM docker.openmodelica.org/build-deps:v1.16.2

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -qy ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && rm -f control requirements.txt *.deb
