# Or ubuntu:bionic
ARG REPO=docker.openmodelica.org/build-deps:v1.16.2
FROM ${REPO}

ARG OCL=16.1.2_x64_rh_6.4.0.37

RUN sed -i s,http://archive.ubuntu.com/ubuntu/,mirror://mirrors.ubuntu.com/mirrors.txt, /etc/apt/sources.list \
    && export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get upgrade -qy && apt-get dist-upgrade -qy\
    && apt-get install -qy gnupg wget ca-certificates apt-transport-https devscripts equivs python3-pip python-pip libmldbm-perl docker.io sudo git subversion texlive-base texlive-latex-extra latexmk gnuplot-nox doxygen poppler-utils flex libgfortran3 aspell bibtex2html zip unzip ocl-icd-opencl-dev cpio xsltproc inkscape g++-4.8 g++-5 g++-6 g++-7 texlive-lang-greek xvfb libcurl4-gnutls-dev \
    && (test "`pandoc --version | head -1`" == "pandoc 2.2.3.2" || (wget https://github.com/jgm/pandoc/releases/download/2.2.3.2/pandoc-2.2.3.2-1-amd64.deb && dpkg -i pandoc-2.2.3.2-1-amd64.deb && apt-get install -qyf)) \
    && wget https://raw.githubusercontent.com/OpenModelica/OpenModelicaBuildScripts/master/debian/control \
    && wget https://raw.githubusercontent.com/OpenModelica/OpenModelica-doc/master/UsersGuide/source/requirements.txt \
    && test -e /opt/intel/opencl || ( \
      wget http://registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_${OCL}.tgz \
      && tar xzvf opencl_runtime_${OCL}.tgz \
      && sed -i -e s/=decline/=accept/ -e s/=RPM/=NONRPM/ opencl_runtime_${OCL}/silent.cfg \
      && (cd opencl_runtime_16.1.2_x64_rh_6.4.0.37 && ./install.sh -s silent.cfg) \
      && rm -rf opencl_runtime_* \
    ) \
    && mk-build-deps --install -t 'apt-get --force-yes -y' control \
    && pip2 install --no-cache-dir --upgrade -r requirements.txt \
    && pip3 install --no-cache-dir --upgrade -r requirements.txt \
    && pip3 install --no-cache-dir --upgrade junit_xml simplejson svgwrite # ComplianceSuite \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && rm -f control requirements.txt *.deb
