FROM docker.openmodelica.org/build-deps:v1.16.3

# Install cmake 3.17.2.
RUN wget cmake.org/files/v3.17/cmake-3.17.2-Linux-x86_64.sh \
    && mkdir -p /opt/cmake-3.17.2 \
    && sh cmake-3.17.2-Linux-x86_64.sh --prefix=/opt/cmake-3.17.2 --skip-license \
    && rm cmake-3.17.2-Linux-x86_64.sh
